[installer]
log_level = 'trace'                          # Example: 'info', 'debug', 'trace'
check_updates = false                    # Set false to skip the startup GitHub version check.
refresh_configs = false                  # Set false to skip pulling remote config files on startup.

[instance]
launcher = ''                           # Example: 'steam', 'gog', 'epic'
theme = 'paper-dark'                              # Example: 'paper-dark'
plugins = ["root-builder"]                            # Example: [ "root-builder", "auto-activator", "fomod-plus", "nxm-collection-dl" ]

[instance.folders]
root_folder = '~/Games/mo2-lint'        # Where the instance folder will be created.
folder_name = 'mo2-{game}-{launcher}'   # The actual instance folder name. Placeholders: {game}, {launcher}

# i.e. root_folder = '~/Games/mo2-lint' and folder_name = 'mo2-{game}-{launcher}' will create the instance folder at '~/Games/mo2-lint/mo2-{game}-{launcher}'
