name: Bug Report
description: Create a report to help us fix issues
title: "[Bug]: "
labels: ['bug']
assignees: Furglitch
body:
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: Describe the expected behavior
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the issue
      value: '1. '
    validations:
      required: false
  - type: markdown
    attributes:
      value: '## Install Environment'
  - type: input
    id: version
    attributes:
      label: Installer version
      description: Do not put 'latest', put the version number
      value: '5.2.X'
    validations:
      required: true
  - type: dropdown
    id: game
    attributes:
      label: Targeted game
      description: Which game are you trying to install?
      options:
        - Cyberpunk 2077
        - Dragon Age: Origins
        - Enderal
        - Enderal SE
        - Fallout 3
        - Fallout 3 GOTY
        - Fallout 4
        - Fallout New Vegas
        - Fallout New Vegas (RU)
        - Morrowind
        - Oblivion
        - Oblivion Remastered
        - Skyrim
        - Skyrim SE
        - Skyrim VR
        - Starfield
        - Multiple / Other (list in 'Additional Info')
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Linux Distro
      description: What distro are you running?
      placeholder: 'ArchLinux, Debian, Fedora, Ubuntu, etc.'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include the logs here. You can find your log file (install.log) in the same folder as install.sh This field is automatically formatted into code, so you do not need to include any backticks.
      placeholder: Paste logs here
      render: shell
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
