source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "jekyll-remote-theme", github: "benbalter/jekyll-remote-theme"

# Remote theme dependencies
gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-seo-tag", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins
# gem "just-the-docs", path: "../../just-the-docs"
