name: Test Builds

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "configs/**"
      - ".pre-commit-config.yaml"
      - ".python-version"
      - "Makefile"
      - "pyproject.toml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "configs/**"
      - ".pre-commit-config.yaml"
      - ".python-version"
      - "Makefile"
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  test-ubuntu:
    name: Ubuntu Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and run ubuntu tests
        run: docker compose -f "./docker/docker-compose.yml" run --build --rm test-ubuntu

  test-debian:
    name: Debian Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and run debian tests
        run: docker compose -f "./docker/docker-compose.yml" run --build --rm test-debian

  test-fedora:
    name: Fedora Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and run fedora tests
        run: docker compose -f "./docker/docker-compose.yml" run --build --rm test-fedora

  test-arch:
    name: Arch Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and run arch tests
        run: docker compose -f "./docker/docker-compose.yml" run --build --rm test-arch

  test-steamos:
    name: SteamOS Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and run steamos tests
        run: docker compose -f "./docker/docker-compose.yml" run --build --rm test-steamos
